-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B 
        JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
        JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY 1,3
ORDER BY 1 , 3 DESC;


# SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE* SALES) TOTAL_SALES
# FROM BOOK B
#     JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
#     JOIN BOOK_SALES S ON B.BOOK_ID = s.BOOK_ID
# WHERE SALES_DATE LIKE '2022-01%'
# GROUP BY A.AUTHOR_ID, CATEGORY
# ORDER BY B.AUTHOR_ID, CATEGORY DESC