-- 코드를 입력하세요
(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE ONS
WHERE DATE_FORMAT(ONS.SALES_DATE,'%Y-%m') = '2022-03')

UNION

(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE OFS
WHERE DATE_FORMAT(OFS.SALES_DATE,'%Y-%m') = '2022-03')

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID