-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, H.EMP_NAME, H.POSITION, H.EMAIL
FROM HR_GRADE G JOIN HR_EMPLOYEES H ON G.EMP_NO = H.EMP_NO
WHERE G.YEAR = '2022'
GROUP BY 2,3,4,5
ORDER BY 1 DESC
LIMIT 1;