-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT 
WHERE (CATEGORY, PRICE) IN (SELECT CATEGORY, MAX(PRICE)
                FROM FOOD_PRODUCT
                GROUP BY CATEGORY 
                HAVING CATEGORY IN ('과자', '국', '김치', '식용유'))
ORDER BY 2 DESC

# SELECT F2.CATEGORY, MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT F1 JOIN (
#     SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
#     FROM FOOD_PRODUCT
#     GROUP BY CATEGORY) AS F2
# ON F1.CATEGORY = F2.CATEGORY
# WHERE F1.PRICE = MAX_PRICE 
# AND F2.CATEGORY IN('과자', '국', '김치', '식용유')
# ORDER BY MAX_PRICE DESC